// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef WATERFALL_ANIMATION_INCLUDE_H
#define WATERFALL_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK2) extern const TileAnimation waterfall;

#endif

