// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef GLOBALPALETTE_PALETTE_INCLUDE_H
#define GLOBALPALETTE_PALETTE_INCLUDE_H

#include "palette_types.h"
#include "resource_types.h"

RESOURCE() extern const PaletteResource globalPalette;

#endif

