// this file was automatically generated by tmx2c. https://github.com/pw32x/tmx2c
#ifndef BACKGROUND3_MAP_INCLUDE_H
#define BACKGROUND3_MAP_INCLUDE_H

#include "map_types.h"

RESOURCE(BANK2) extern const Map const background3_map;

#endif
