// this file was automatically generated by tmx2c. https://github.com/pw32x/tmx2c
#ifndef LEVEL_001_MAP_INCLUDE_H
#define LEVEL_001_MAP_INCLUDE_H

#include "map_types.h"

RESOURCE(BANK4) extern const Map const level_001_map;

#endif
