// this file was automatically generated by tmx2c. https://github.com/pw32x/tmx2c
#include "waterfall.h"
#include "resource_types.h"

// array of metatile indexes. use the metatile look up table to figure out which actual 8x8 tiles to use.
const unsigned short const waterfall_metatile_map[2] = 
{
    0,
    1,
    
};


extern ResourceInfo waterfall_tilesetResourceInfo;


const ResourceInfo* waterfall_tilesetResourceInfos[1] = 
{
    &waterfall_tilesetResourceInfo, // Tileset
};

RESOURCE(BANK4) const Map const waterfall_map = 
{
    MAP_RESOURCE_TYPE,
    waterfall_metatile_map, // metatile index map data
    waterfall_tilesetResourceInfos, // tilesets used in the map
    1, // number of tilesets used by this map
    1, // metatile map width
    2, // metatile map height
};

