// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef COLORTWEAKERCURSOR_ANIM_ANIMATION_INCLUDE_H
#define COLORTWEAKERCURSOR_ANIM_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK2) extern const MetaSpriteAnimation colorTweakerCursor_anim;

#define COLORTWEAKERCURSOR_ANIM_NUMFRAMES 5

#endif

