// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef COLORTWEAKERCURSOR_ANIMATION_INCLUDE_H
#define COLORTWEAKERCURSOR_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK2) extern const BatchedAnimation colorTweakerCursor;

#endif

