// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef EXPLOSION_ANIMATION_INCLUDE_H
#define EXPLOSION_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK2) extern const BatchedAnimation explosion;

// frame numbers for specific animations.
#define EXPLOSION_16_FRAME_INDEX 3
#define EXPLOSION_16_FRAME_INDEX 3
#define EXPLOSION_16_FRAME_INDEX 6
#define EXPLOSION_16_FRAME_INDEX 6

#endif

