// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef EXPLOSION_ANIM_ANIMATION_INCLUDE_H
#define EXPLOSION_ANIM_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK2) extern const MetaSpriteAnimation explosion_anim;

#define EXPLOSION_ANIM_NUMFRAMES 9

#endif

