// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef IMPACT_ANIM_ANIMATION_INCLUDE_H
#define IMPACT_ANIM_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK2) extern const MetaSpriteAnimation impact_anim;

#define IMPACT_ANIM_NUMFRAMES 3

// frame numbers for specific animations.
#define IMPACT_ANIM_8_FRAME_INDEX 0
#define IMPACT_ANIM_8_FRAME_INDEX 0

#endif

