// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef KUNAI_ANIM_ANIMATION_INCLUDE_H
#define KUNAI_ANIM_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK2) extern const MetaSpriteAnimation kunai_anim;

#define KUNAI_ANIM_NUMFRAMES 8

#endif

