// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef ROCK_PARTICLE_ANIMATION_INCLUDE_H
#define ROCK_PARTICLE_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK2) extern const MetaSpriteAnimation rock_particle;

#endif

