// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef TEST_BLOCK_ANIMATION_INCLUDE_H
#define TEST_BLOCK_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK2) extern const MetaSpriteAnimation test_block;

#define TEST_BLOCK_NUMFRAMES 1

// frame numbers for specific animations.
#define TEST_BLOCK_RUN_RIGHT_FRAME_INDEX 0

#endif

