// this file was automatically generated by tmx2c. https://github.com/pw32x/tmx2c
#ifndef BACKGROUND_MAP_INCLUDE_H
#define BACKGROUND_MAP_INCLUDE_H

#include "map_types.h"

extern const Map const background_map;

#endif
