// this file was automatically generated by tmx2c. https://github.com/pw32x/tmx2c
#ifndef BACKGROUND2_MAP_INCLUDE_H
#define BACKGROUND2_MAP_INCLUDE_H

#include "map_types.h"

extern const Map const background2_map;

#endif
