// File generated by gg2c. https://github.com/pw32x/gg2c
#ifndef BIRDIDLE_ANIMATION_INCLUDE_H
#define BIRDIDLE_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

extern const PlaneAnimation birdidle;

#endif

