// File generated by gg2c. https://github.com/pw32x/gg2c
#ifndef EVIL_EYE_ANIMATION_INCLUDE_H
#define EVIL_EYE_ANIMATION_INCLUDE_H

#include "animation_types.h"

extern const Animation evil_eye;

#endif

