// File generated by gg2c. https://github.com/pw32x/gg2c
#ifndef EVIL_EYE_ANIMATION_INCLUDE_H
#define EVIL_EYE_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

extern const BatchedAnimation evil_eye;

// frame numbers for specific animations.

#endif

