// File generated by gg2c. https://github.com/pw32x/gg2c
#ifndef IMPACT_ANIMATION_INCLUDE_H
#define IMPACT_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

extern const BatchedAnimation impact;

// frame numbers for specific animations.

#endif

