// File generated by gg2c. https://github.com/pw32x/gg2c
#ifndef KUNAI_ANIMATION_INCLUDE_H
#define KUNAI_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

extern const BatchedAnimation kunai;

// frame numbers for specific animations.

#endif

