// File generated by gg2c. https://github.com/pw32x/gg2c
#ifndef NINJA_BOY_ANIMATION_INCLUDE_H
#define NINJA_BOY_ANIMATION_INCLUDE_H

#include "animation_types.h"

extern const Animation ninja_boy;

#endif

