// File generated by gg2c. https://github.com/pw32x/gg2c
#ifndef NINJA_GIRL_ANIMATION_INCLUDE_H
#define NINJA_GIRL_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

extern const StreamedBatchedAnimation ninja_girl;

// frame numbers for specific animations.
#define NINJA_GIRL_RUN_RIGHT_FRAME_INDEX 0
#define NINJA_GIRL_RUN_LEFT_FRAME_INDEX 3
#define NINJA_GIRL_STAND_RIGHT_FRAME_INDEX 6
#define NINJA_GIRL_STAND_LEFT_FRAME_INDEX 7
#define NINJA_GIRL_JUMP_RIGHT_FRAME_INDEX 8
#define NINJA_GIRL_FALL_RIGHT_FRAME_INDEX 9
#define NINJA_GIRL_JUMP_LEFT_FRAME_INDEX 10
#define NINJA_GIRL_FALL_LEFT_FRAME_INDEX 11

#endif

