// File generated by gg2c. https://github.com/pw32x/gg2c
#ifndef ROCK_PARTICLE_ANIMATION_INCLUDE_H
#define ROCK_PARTICLE_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

extern const Animation rock_particle;

#endif

