// File generated by gg2c. https://github.com/pw32x/gg2c
#ifndef WATERFALL_ANIMATION_INCLUDE_H
#define WATERFALL_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

extern const TileAnimation waterfall;

// frame numbers for specific animations.
#define WATERFALL_RUN_RIGHT_FRAME_INDEX 0
#define WATERFALL_RUN_LEFT_FRAME_INDEX 2
#define WATERFALL_STAND_RIGHT_FRAME_INDEX 4
#define WATERFALL_STAND_LEFT_FRAME_INDEX 5
#define WATERFALL_JUMP_RIGHT_FRAME_INDEX 6
#define WATERFALL_FALL_RIGHT_FRAME_INDEX 7
#define WATERFALL_JUMP_LEFT_FRAME_INDEX 8
#define WATERFALL_FALL_LEFT_FRAME_INDEX 9

#endif

