// File generated by gg2c. https://github.com/pw32x/gg2c
#ifndef WATER_TILES_ANIMATION_INCLUDE_H
#define WATER_TILES_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

extern const Animation water_tiles;

// frame numbers for specific animations.
#define WATER_TILES_RUN_RIGHT_FRAME_INDEX 0
#define WATER_TILES_RUN_LEFT_FRAME_INDEX 2
#define WATER_TILES_STAND_RIGHT_FRAME_INDEX 4
#define WATER_TILES_STAND_LEFT_FRAME_INDEX 5
#define WATER_TILES_JUMP_RIGHT_FRAME_INDEX 6
#define WATER_TILES_FALL_RIGHT_FRAME_INDEX 7
#define WATER_TILES_JUMP_LEFT_FRAME_INDEX 8
#define WATER_TILES_FALL_LEFT_FRAME_INDEX 9

#endif

