// File generated by gg2c. https://github.com/pw32x/gg2c
#ifndef WATER_TILES_ANIMATION_INCLUDE_H
#define WATER_TILES_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

extern const AnimationBatched water_tiles;

#endif

