// this file was automatically generated by tmx2c. https://github.com/pw32x/tmx2c
#ifndef FIELD_MAP_INCLUDE_H
#define FIELD_MAP_INCLUDE_H

#include "map_types.h"

RESOURCE(BANK4) extern const StripMap const field_map;

#endif
