// this file was automatically generated by tmx2c. https://github.com/pw32x/tmx2c
#include "waterfall.h"
#include "resource_types.h"

extern const ResourceInfo waterfall_tilesetResourceInfo;


const unsigned short const waterfall_strip_map[8] = // 2 x 4
{
    444, 446, 445, 447, 
    956, 958, 957, 959, 
    
};


const unsigned char const waterfall_terrain_map[2] = // 1 x 2
{
    0,0,
    
};

RESOURCE(BANK4) const StripMap const waterfall_map = 
{
    STRIP_MAP_RESOURCE_TYPE,
    waterfall_strip_map, // strip map data
    &waterfall_tilesetResourceInfo, 
    2, // map width
    4, // map height
    waterfall_terrain_map, // terrain map data
    1, // terrain map width
    2, // terrain map height
};

