// this file was automatically generated by tmx2c. https://github.com/pw32x/tmx2c
#ifndef WATERFALL_MAP_INCLUDE_H
#define WATERFALL_MAP_INCLUDE_H

#include "map_types.h"

RESOURCE(BANK4) extern const StripMap const waterfall_map;

#endif
