#include "..\stdafx.h"
#include "Animation.h"

#include "..\Base\TileStore.h"
#include "..\GraphicsGale\GraphicsGaleObject.h"
#include "..\Utils\StringUtils.h"
#include "..\Utils\WriteUtils.h"

#include <algorithm>
#include <fstream>
#include <sstream>

namespace SpriteMaster
{

GGAnimation::GGAnimation(const GraphicsGaleObject& ggo, 
                         bool streamed,
                         bool isMetaSprite)
: m_ggo(ggo)
, m_isStreamed(streamed)
, m_isMetaSprite(isMetaSprite)
{
    HBITMAP bitmap = m_ggo.getBitmap(0, 0);

    if (bitmap == NULL)
    {
		printf("Error retrieving bitmap data");
		exit(-1);
    }

    if (GetObject(bitmap, sizeof(BITMAP), &m_generalBitmapInfo) == 0)
    {
        printf("BitmapInfo is NULL\n");
		exit(-1);
    }

    unsigned int numberOfFrames = m_ggo.getFrameCount();
	m_frames.resize(numberOfFrames);

    m_maxTilesInFrame = 0;

    for (DWORD loop = 0; loop < numberOfFrames; loop++)
    {
		GGAnimationFrame& frame = m_frames[loop];

		frame.Init(loop, 
                   m_ggo, 
                   m_spriteStripStore,
                   m_animationProperties);

        m_maxTilesInFrame = max(m_maxTilesInFrame, frame.GetMaxTilesInAFrame());

		m_totalFrameTime += frame.GetFrameDelayTime();

        if (loop > 0)
        {
            int previousIndex = loop - 1;

            GGAnimationFrame& previousFrame = m_frames[previousIndex];

            if (previousFrame.getNextFrameIndex() == AnimationFrameBase::NEXT_FRAME_NOT_SET)
            {
                if (frame.startsAnimation())
                {
                    int animationStartIndex;

                    auto it = m_animationProperties.animationFrameNames.lower_bound(loop);

                    if (it != m_animationProperties.animationFrameNames.begin()) 
                    {
                        --it; // Move the iterator one step back to get the closest key
                        animationStartIndex = it->first;
                    } 
                    else 
                    {
                        animationStartIndex = 0;
                    }

                    previousFrame.setNextFrameIndex(animationStartIndex);
                }
                else
                {
                    previousFrame.setNextFrameIndex(loop);
                }
            }
        }
    }

    int lastFrameIndex = m_frames.size() - 1;

    if (m_frames[lastFrameIndex].getNextFrameIndex() == AnimationFrameBase::NEXT_FRAME_NOT_SET)
    {
        if (!m_frames[lastFrameIndex].startsAnimation())
        {
            auto it = m_animationProperties.animationFrameNames.lower_bound(lastFrameIndex);

            if (it != m_animationProperties.animationFrameNames.begin()) 
            {
                --it; // Move the iterator one step back to get the closest key
                m_frames[lastFrameIndex].setNextFrameIndex(it->first);
            } 
            else 
            {
                m_frames[lastFrameIndex].setNextFrameIndex(0);
            }
        }
        else
        {
            m_frames[lastFrameIndex].setNextFrameIndex(lastFrameIndex);
        }
    }
}

void GGAnimation::Write(const std::string& outputFolder, const std::string& outputName, const std::string& bank)
{
	WriteGGAnimationHeaderFile(outputFolder, outputName, bank);
	WriteGGAnimationSourceFile(outputFolder, outputName, bank);
}


void GGAnimation::WriteGGAnimationHeaderFile(const std::string& outputFolder, 
                                             const std::string& outputName,
                                             const std::string& bank)
{
	std::string headerFilename = outputName + ".h";
	std::ofstream headerfile(outputFolder + headerFilename, std::ios::trunc);

    // header guard
    std::string headerGuard = outputName + "_ANIMATION_INCLUDE_H";
    std::transform(headerGuard.begin(), headerGuard.end(), headerGuard.begin(), ::toupper);
    headerfile << "// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl\n";
    headerfile << "#ifndef " << headerGuard << "\n";
    headerfile << "#define " << headerGuard << "\n";
    headerfile << "\n";

	// includes
    headerfile << "#include \"animation_types.h\"\n";
    headerfile << "#include \"resource_types.h\"\n";
    headerfile << "\n";

	// exported types

    if (m_isMetaSprite)
        headerfile << "RESOURCE(" << bank << ") extern const MetaSpriteAnimation " << outputName << ";\n"; 
    else
        headerfile << "RESOURCE(" << bank << ") extern const BatchedAnimation " << outputName << ";\n"; 

    headerfile << "\n";

    if (m_animationProperties.animationFrameNames.size() > 0)
    {
        headerfile << "// frame numbers for specific animations.\n";
        for (const auto& pair : m_animationProperties.animationFrameNames) 
	    {
		    std::transform(headerGuard.begin(), headerGuard.end(), headerGuard.begin(), ::toupper);
		    headerfile << "#define " << StringUtils::str_toupper(outputName) << "_" << StringUtils::str_toupper(pair.second) << "_FRAME_INDEX" << " " << pair.first << "\n";
        }
        headerfile << "\n";
    }

    // end header guard
    headerfile << "#endif\n\n";
    headerfile.close();
}

void GGAnimation::WriteSpritesBatched(const std::string& outputName, std::ofstream& sourceFile)
{
	for (size_t frameLoop = 0; frameLoop < m_frames.size(); frameLoop++)
	{
		const GGAnimationFrame& frame = m_frames[frameLoop];

        if (m_isMetaSprite)
        {
            // devkitSMS metasprites
            std::string metaSpriteName = WriteUtils::BuildFrameName(outputName, frameLoop) + "MetaSprites";
            sourceFile << "const s8 " << metaSpriteName << "[] = \n";
            sourceFile << "{\n";

            for (const auto& sprite : frame.getSprites())
            {
                int x = sprite.m_xPositionOffset - m_animationProperties.mOffsetX;
                int y = sprite.m_yPositionOffset - m_animationProperties.mOffsetY;
                int tileIndex = sprite.m_spriteStrip.tileStartIndex;

                for (int loop = 0; loop < sprite.m_spriteStrip.count; loop++)
                {
                    sourceFile << "    " << x << ", " << y << ", " << tileIndex << ",\n";
                    x += 8;
                    tileIndex += 2;
                }
            }

            sourceFile << "    (s8)0x80 // end marker\n";
            sourceFile << "};\n\n";
        }
        else
        {
            // strips

            std::string spriteStripName = WriteUtils::BuildFrameName(outputName, frameLoop) + "SpriteStrips";

            sourceFile << "const BatchedAnimationSpriteStrip " << spriteStripName << "[] = \n";
            sourceFile << "{\n";

            for (const auto& sprite : frame.getSprites())
            {
                sourceFile << "    { ";
                sourceFile << sprite.m_spriteStrip.count << ", ";
                sourceFile << sprite.m_xPositionOffset - m_animationProperties.mOffsetX << ", ";
                sourceFile << sprite.m_yPositionOffset - m_animationProperties.mOffsetY << ", ";
                sourceFile << sprite.m_spriteStrip.tileStartIndex;
                sourceFile << " },\n";
            }
            sourceFile << "    {0},\n";
            sourceFile << "};\n\n";
        }
    }
}

void GGAnimation::WriteFramesBatched(const std::string& outputName, std::ofstream& sourceFile)
{
	for (size_t frameLoop = 0; frameLoop < m_frames.size(); frameLoop++)
	{
		const GGAnimationFrame& frame = m_frames[frameLoop];
        std::string frameName = WriteUtils::BuildFrameName(outputName, frameLoop);

        if (m_isMetaSprite)
            sourceFile << "extern const MetaSpriteAnimationFrame " << frameName << ";\n";
        else
            sourceFile << "extern const BatchedAnimationFrame " << frameName << ";\n";
	}

    sourceFile << "\n";

	for (size_t frameLoop = 0; frameLoop < m_frames.size(); frameLoop++)
	{
		const GGAnimationFrame& frame = m_frames[frameLoop];

        std::string frameName = WriteUtils::BuildFrameName(outputName, frameLoop);
        std::string nextFrameName;
        

        if (frame.getNextFrameIndex() == AnimationFrameBase::NO_LOOP)
            //nextFrameName = "NULL";
            nextFrameName = "&" + WriteUtils::BuildFrameName(outputName, frame.getFrameNumber());
        else
            nextFrameName = "&" + WriteUtils::BuildFrameName(outputName, frame.getNextFrameIndex());

		sourceFile << "\n";

        if (m_isMetaSprite)
            sourceFile << "const MetaSpriteAnimationFrame " << frameName << " = \n";
        else
		    sourceFile << "const BatchedAnimationFrame " << frameName << " = \n";

		sourceFile << "{\n";

        if (m_isMetaSprite)
            sourceFile << "    " << frameName << "MetaSprites,\n";
        else
            sourceFile << "    " << frameName << "SpriteStrips,\n";

		sourceFile << "    " << frame.GetFrameDelayTime() << ", // frame time\n"; 
        sourceFile << "    " << nextFrameName << ", // next frame\n";
		sourceFile << "};\n";
	}
}

void GGAnimation::WriteFrameArrayBatched(const std::string& outputName, std::ofstream& sourceFile)
{
    if (m_isMetaSprite)
        sourceFile << "const MetaSpriteAnimationFrame* const " << outputName << "Frames[" << m_frames.size() << "] = \n";
    else
        sourceFile << "const BatchedAnimationFrame* const " << outputName << "Frames[" << m_frames.size() << "] = \n";

    sourceFile << "{\n";

    for (size_t loop = 0; loop < m_frames.size(); loop++)
    {
        sourceFile << "    &" << WriteUtils::BuildFrameName(outputName, loop) << ",\n";
    }

    sourceFile << "};\n\n";
}

void GGAnimation:: WriteAnimationStructBatched(const std::string& outputName, 
                                               std::ofstream& sourceFile,
                                               const std::string& bank)
{
    sourceFile << "u8 " << outputName << "VdpLocation;\n\n";

    // final struct
    if (m_isMetaSprite)
        sourceFile << "const MetaSpriteAnimation " << outputName << " = \n";
    else
        sourceFile << "const BatchedAnimation " << outputName << " = \n";

    sourceFile << "{\n";

    if (m_isStreamed)
        sourceFile << "    STREAMED_BATCHED_ANIMATION_RESOURCE_TYPE, \n";
    else if (m_isMetaSprite)
        sourceFile << "    METASPRITE_ANIMATION_RESOURCE_TYPE, \n";
    else
        sourceFile << "    BATCHED_ANIMATION_RESOURCE_TYPE, \n";

    if (m_isMetaSprite)
        sourceFile << "    (const MetaSpriteAnimationFrame** const)" << outputName << "Frames,\n";
    else
        sourceFile << "    (const BatchedAnimationFrame** const)" << outputName << "Frames,\n";

    sourceFile << "    (unsigned char* const)" << outputName << "TileData, // start of the sprite data\n";
    sourceFile << "    " << m_frames.size() << ", // number of frames\n";
    sourceFile << "    " << m_generalBitmapInfo.bmWidth << ", // width in pixels\n";
    sourceFile << "    " << m_generalBitmapInfo.bmHeight << ", // height in pixels\n";
    sourceFile << "    " << m_spriteStripStore.GetTileCount() << ", // the total amount of tiles in animation\n";
    sourceFile << "    " << m_maxTilesInFrame << ", // the max amount of sprite tiles in a frame\n";    
    sourceFile << "    &" << outputName << "VdpLocation,\n";
    sourceFile << "};\n";
}

void GGAnimation::WriteGGAnimationSourceFile(const std::string& outputFolder, 
                                             const std::string& outputName,
                                             const std::string& bank)
{
	std::ofstream sourceFile(outputFolder + outputName + ".c");

    // includes
    sourceFile << "#include \"" << outputName << ".h\"\n";
	
    sourceFile << "\n";
    sourceFile << "\n";

	// tile data
    m_spriteStripStore.WriteTileStore(outputName, sourceFile);

    WriteSpritesBatched(outputName, sourceFile);
    WriteFramesBatched(outputName, sourceFile);
	WriteFrameArrayBatched(outputName, sourceFile);
    WriteAnimationStructBatched(outputName, sourceFile, bank);


    sourceFile.close();
}

/*
#include "player.h"


unsigned short const playerTileData[32] = 
{
// tile: 0
    0x0000, 0x22,
    0x0000, 0x2ee,
    0x0000, 0x2eee,
    0x0000, 0x29e9,
    0x0002, 0x9ee6,
    0x0002, 0xee66,
    0x002e, 0xfe6e,
    0x002e, 0xfe9c,

	[...]

};

const Sprite playerFrame0Sprites[] =
{
	x, y, n,
	x, y, n,
	[...]
};

const Sprite playerFrame0XFlippedSprites[] =
{
	x, y, n,
	x, y, n,
	[...]
};

(align to 4)
const AnimationFrame playerFrame0 =
{
	playerFrame0Sprites
	0, // frame time
	X, // num sprites
}

(align to 4)
const AnimationFrame playerFrame0XFlipped =
{
	playerFrame0XFlippedSprites
	0, // frame time
	X, // num sprites

}

const AnimationFrames* playerFrames[] = // need pointers???
{
	playerFrame0,
	playerFrame0XFlipped
};

(align to 4)
const Animation player_animation =
{
    playerFrames,										(unsigned int)
    (u32*)playerTileData, // start of the sprite data	(unsigned int)
    2, // number of frames								(unsigned char)
    24, // width in pixels								(unsigned char)
    32, // height in pixels								(unsigned char)
    12, // max tiles per frame							(unsigned char)
    20, // the total number of tiles in the animation	(unsigned char)
    118, // the total time of the animation				(unsigned short)
};



*/

}