// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef ENEMY_BULLET_ANIMATION_INCLUDE_H
#define ENEMY_BULLET_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK6) extern const BatchedAnimation enemy_bullet;

#endif

