// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef ROBOTSPRING_ANIM_ANIMATION_INCLUDE_H
#define ROBOTSPRING_ANIM_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK6) extern const MetaSpriteAnimation robotspring_anim;

#define ROBOTSPRING_ANIM_NUMFRAMES 3

#endif

