// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef ROBOTRUNNER_ANIM_ANIMATION_INCLUDE_H
#define ROBOTRUNNER_ANIM_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK6) extern const MetaSpriteAnimation robotrunner_anim;

#define ROBOTRUNNER_ANIM_NUMFRAMES 4

// frame numbers for specific animations.
#define ROBOTRUNNER_ANIM_RUN_RIGHT_FRAME_INDEX 0
#define ROBOTRUNNER_ANIM_RUN_LEFT_FRAME_INDEX 2

#endif

