// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef ROBOTRUNNER_ANIMATION_INCLUDE_H
#define ROBOTRUNNER_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK6) extern const BatchedAnimation robotrunner;

// frame numbers for specific animations.
#define ROBOTRUNNER_RUN_RIGHT_FRAME_INDEX 0
#define ROBOTRUNNER_RUN_LEFT_FRAME_INDEX 2

#endif

