// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef THREESHOTFLYER_ANIMATION_INCLUDE_H
#define THREESHOTFLYER_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK6) extern const BatchedAnimation threeshotflyer;

#endif

