// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef THREESHOTFLYER_ANIM_ANIMATION_INCLUDE_H
#define THREESHOTFLYER_ANIM_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK6) extern const MetaSpriteAnimation threeshotflyer_anim;

#define THREESHOTFLYER_ANIM_NUMFRAMES 2

#endif

