// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef WALKER_BIG_ANIMATION_INCLUDE_H
#define WALKER_BIG_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK6) extern const MetaSpriteAnimation walker_big;

// frame numbers for specific animations.
#define WALKER_BIG_RUN_RIGHT_FRAME_INDEX 0
#define WALKER_BIG_RUN_LEFT_FRAME_INDEX 4

#endif

