// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef WALKER_SMALL_ANIMATION_INCLUDE_H
#define WALKER_SMALL_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK6) extern const MetaSpriteAnimation walker_small;

#endif

