// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef WHEELER_ANIM_ANIMATION_INCLUDE_H
#define WHEELER_ANIM_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK6) extern const MetaSpriteAnimation wheeler_anim;

#define WHEELER_ANIM_NUMFRAMES 11

// frame numbers for specific animations.
#define WHEELER_ANIM_RUN_RIGHT_FRAME_INDEX 0
#define WHEELER_ANIM_RUN_LEFT_FRAME_INDEX 2
#define WHEELER_ANIM_SHOCK_FRAME_INDEX 4
#define WHEELER_ANIM_SENTRY_FRAME_INDEX 5
#define WHEELER_ANIM_PARTS_HEAD_FRAME_INDEX 7
#define WHEELER_ANIM_PARTS_ARM1_FRAME_INDEX 8
#define WHEELER_ANIM_PARTS_ARM2_FRAME_INDEX 9
#define WHEELER_ANIM_PARTS_WHEEL_FRAME_INDEX 10

#endif

