#ifndef BASE_DEFINES_INCLUDE_H
#define BASE_DEFINES_INCLUDE_H

#define SCREEN_WIDTH	256
#define SCREEN_HEIGHT	192

#define HALF_SCREEN_WIDTH	128

#define SCREEN_LEFT		8
#define SCREEN_RIGHT	SCREEN_WIDTH
#define SCREEN_TOP		0
#define SCREEN_BOTTOM	SCREEN_HEIGHT

#define TILE_WIDTH		8
#define TILE_HEIGHT		8

// global palette color indexes
#define COLOR_BLACK			0
#define COLOR_DARK_BROWN	1
#define COLOR_DARK_BLUE		2
#define COLOR_DARK_GREY		3
#define COLOR_BROWN			4
#define COLOR_DARK_GREEN	5
#define COLOR_RED			6
#define COLOR_GRAY			7
#define COLOR_BLUE			8
#define COLOR_ORANGE		9
#define COLOR_LIGHT_GREY	10
#define COLOR_LIGHT_GREEN	11
#define COLOR_PINK			12
#define COLOR_LIGHT_BLUE	13
#define COLOR_YELLOW		14
#define COLOR_WHITE			15

#endif