#ifndef RESOURCE_TYPES_INCLUDE_H
#define RESOURCE_TYPES_INCLUDE_H

#define REGULAR_ANIMATION_RESOURCE_TYPE				0
#define STREAMED_REGULAR_ANIMATION_RESOURCE_TYPE	1
#define BATCHED_ANIMATION_RESOURCE_TYPE				2
#define STREAMED_BATCHED_ANIMATION_RESOURCE_TYPE	3
#define PLANE_ANIMATION_RESOURCE_TYPE				4
#define TILE_ANIMATION_RESOURCE_TYPE				5
#define MAP_RESOURCE_TYPE							6
#define TILESET_RESOURCE_TYPE						7
#define ANIMATED_TILESET_RESOURCE_TYPE				8
#define NUM_RESOURCE_TYPES							9

#endif