#ifndef RESOURCE_TYPES_INCLUDE_H
#define RESOURCE_TYPES_INCLUDE_H

#define REGULAR_ANIMATION_RESOURCE_TYPE	0
#define BATCHED_ANIMATION_RESOURCE_TYPE 1
#define PLANE_ANIMATION_RESOURCE_TYPE   2
#define NUM_RESOURCE_TYPES				3

#endif