#ifndef RESOURCE_TYPES_INCLUDE_H
#define RESOURCE_TYPES_INCLUDE_H

#define REGULAR_ANIMATION_RESOURCE_TYPE				0
#define REGULAR_STREAMED_ANIMATION_RESOURCE_TYPE	1
#define BATCHED_ANIMATION_RESOURCE_TYPE				2
#define BATCHED_STREAMED_ANIMATION_RESOURCE_TYPE	3
#define PLANE_ANIMATION_RESOURCE_TYPE				4
#define MAP_RESOURCE_TYPE							5
#define NUM_RESOURCE_TYPES							6

#endif