// File generated by gg2c. https://github.com/pw32x/gg2c
#ifndef IMPACT_ANIMATION_INCLUDE_H
#define IMPACT_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK2) extern const BatchedAnimation impact;

#endif

