// File generated by gg2c. https://github.com/pw32x/gg2c
#ifndef WALKER_BIG_ANIMATION_INCLUDE_H
#define WALKER_BIG_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK2) extern const BatchedAnimation walker_big;

#endif

