// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef WHEELER_ANIMATION_INCLUDE_H
#define WHEELER_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK2) extern const BatchedAnimation wheeler;

// frame numbers for specific animations.
#define WHEELER_RUN_RIGHT_FRAME_INDEX 0
#define WHEELER_RUN_LEFT_FRAME_INDEX 2
#define WHEELER_SHOCK_FRAME_INDEX 4
#define WHEELER_SENTRY_FRAME_INDEX 5
#define WHEELER_PARTS_HEAD_FRAME_INDEX 7
#define WHEELER_PARTS_ARM1_FRAME_INDEX 8
#define WHEELER_PARTS_ARM2_FRAME_INDEX 9
#define WHEELER_PARTS_WHEEL_FRAME_INDEX 10

#endif

