// File generated by gg2c. https://github.com/pw32x/gg2c
#ifndef NINJA_GIRL_ANIMATION_INCLUDE_H
#define NINJA_GIRL_ANIMATION_INCLUDE_H

#include "AnimationTypes.h"

extern const Animation ninja_girl;

#endif

