// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef BULLET_ANIM_ANIMATION_INCLUDE_H
#define BULLET_ANIM_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK5) extern const MetaSpriteAnimation bullet_anim;

#define BULLET_ANIM_NUMFRAMES 1

#endif

