// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef BULLET_ANIMATION_INCLUDE_H
#define BULLET_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK5) extern const MetaSpriteAnimation bullet;

#endif

