// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef DELIVERYROBOT_ANIM_ANIMATION_INCLUDE_H
#define DELIVERYROBOT_ANIM_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK5) extern const MetaSpriteAnimation deliveryrobot_anim;

#define DELIVERYROBOT_ANIM_NUMFRAMES 6

// frame numbers for specific animations.
#define DELIVERYROBOT_ANIM_RIGHT_FRAME_INDEX 0
#define DELIVERYROBOT_ANIM_LEFT_FRAME_INDEX 2
#define DELIVERYROBOT_ANIM_PARTS1_FRAME_INDEX 4
#define DELIVERYROBOT_ANIM_PARTS2_FRAME_INDEX 5

#endif

