// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef SHOTGUN_BULLET_ANIM_ANIMATION_INCLUDE_H
#define SHOTGUN_BULLET_ANIM_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK5) extern const MetaSpriteAnimation shotgun_bullet_anim;

#define SHOTGUN_BULLET_ANIM_NUMFRAMES 3

// frame numbers for specific animations.
#define SHOTGUN_BULLET_ANIM_RUN_RIGHT_FRAME_INDEX 0

#endif

