// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef SHOTGUN_ITEM_ANIMATION_INCLUDE_H
#define SHOTGUN_ITEM_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK5) extern const MetaSpriteAnimation shotgun_item;

#define SHOTGUN_ITEM_NUMFRAMES 1

#endif

