// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef SHOTGUN_ANIMATION_INCLUDE_H
#define SHOTGUN_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE(BANK5) extern const MetaSpriteAnimation shotgun;

// frame numbers for specific animations.
#define SHOTGUN_RUN_RIGHT_FRAME_INDEX 0

#endif

